# Use the latest Ubuntu base image
FROM ubuntu:latest

# Update APT package list
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Default command executed when container runs
CMD echo "Hello, World!"
